- create:
    - ~/.config/bat

- crossplatform-link:
    - ~/.config/bat/themes:
        platform: "!win32"
        path: bat/themes

- crossplatform-shell:
    # rebuild the bat cache with the new theme
    - command: bat cache --build
      platform: "!win32"
