- crossplatform-shell:
    - nix-env -iA nixpkgs.fd nixpkgs.unzip nixpkgs.trash-cli nixpkgs.ripgrep
    - nix-env -iA nixpkgs.fzf nixpkgs.lsd nixpkgs.delta nixpkgs.deno nixpkgs.go
    - nix-env -iA nixpkgs.bat nixpkgs.jq nixpkgs.imagemagick nixpkgs.graphviz nixpkgs.thefuck
