- crossplatform-shell:
    - sudo apt update && sudo apt install build-essential cmake fd-find rename libfuse2 unzip trash-cli sqlite3 libsqlite3-dev python-is-python3  -y
    - sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep -y
    - sudo apt install golang-go shellcheck chafa jq imagemagick imagemagick-doc git-gui graphviz -y
    - command: sudo apt install kdiff3 xclip -y
      platform: linux
      environment: "!WSL_DISTRO_NAME"
    - command: sudo apt install wl-clipboard xdg-utils -y
      platform: linux
      environment: "WSL_DISTRO_NAME"
