- crossplatform-shell:
    - nix-env -iA nixpkgs.mcfly nixpkgs.fd nixpkgs.unzip nixpkgs.trash-cli nixpkgs.ripgrep
    - nix-env -iA nixpkgs.bat nixpkgs.jq nixpkgs.imagemagick nixpkgs.graphviz
    - nix-env -iA nixpkgs.fzf nixpkgs.lsd nixpkgs.delta nixpkgs.deno
