- crossplatform-shell:
    - command: >
        rm -f ~/Downloads/UbuntuMono.zip
        && wget -O ~/Downloads/UbuntuMono.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.zip
        && unzip ~/Downloads/UbuntuMono.zip -d ~/.fonts
        && fc-cache -fv
        && rm -v ~/Downloads/UbuntuMono.zip
      platform: linux
