- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitconfig-work: git/gitconfig-work
    ~/.gitignore: git/global-gitignore

- crossplatform-link:
  - ~/.gitconfig-credential: 
      environment: WSL_DISTRO_NAME
      path: git/gitconfig-credential-wsl
  - ~/.gitconfig-credential: 
      environment: "!WSL_DISTRO_NAME"
      path: git/gitconfig-credential-store
