- crossplatform-link:
    ~/.gitconfig: git/gitconfig
    ~/.gitconfig-work: git/gitconfig-work
    ~/.gitignore: git/global-gitignore

- crossplatform-link:
    - ~/.gitconfig-credential:
        platform: linux
        environment: WSL_DISTRO_NAME
        path: git/gitconfig-credential-wsl
    - ~/.gitconfig-credential:
        platform: linux
        environment: "!WSL_DISTRO_NAME"
        path: git/gitconfig-credential-store
    - ~/.gitconfig-credential:
        platform: win32
        path: git/gitconfig-credential-store
