- crossplatform-link:
    ~/.gitconfig: git/gitconfig
    ~/.gitconfig-work: git/gitconfig-work
    ~/.gitignore: git/global-gitignore

- crossplatform-link:
    - ~/.gitconfig-credential:
        platform: linux
        environment: "WSL_DISTRO_NAME"
        path: git/gitconfig-credential-wsl
    - ~/.gitconfig-credential:
        platform: linux
        environment: "!WSL_DISTRO_NAME"
        path: git/gitconfig-credential-oauth
    - ~/.gitconfig-credential:
        platform: win32
        path: git/gitconfig-credential-store
    - ~/.gitconfig-credential:
        platform: darwin
        path: git/gitconfig-credential-manager-mac
- crossplatform-shell:
    - command: sudo add-apt-repository ppa:git-core/ppa && sudo apt update && sudo apt install git -y
      platform: linux
      environment: "!ARCH_DISTRO_NAME"
    - command: nix-env -iA nixpkgs.git-credential-oauth
      platform: linux
    - command: brew install --cask git-credential-manager
      platform: darwin
