- crossplatform-shell:
  - command: deno install --allow-run --allow-env --allow-net --allow-read --unstable --no-check https://raw.githubusercontent.com/1DIce/gitlab-cli/main/gitlab-cli.ts
    platform: win32