- link:
    ~/.config/gitui/key_bindings.ron: gitui/key_bindings.ron

- shell:
  - wget -O ~/Downloads/gitui.tar.gz https://github.com/extrawurst/gitui/releases/latest/download/gitui-linux-musl.tar.gz
  - tar zxvf ~/Downloads/gitui.tar.gz -C ~/bin/
  - rm -v ~/Downloads/gitui.tar.gz
