- create:
    - ~/.config/gitui

- crossplatform-link:
    - ~/.config/gitui/key_bindings.ron:
        path: gitui/key_bindings.ron
        platform: linux
    - ~/AppData/Roaming/gitui/key_bindings.ron:
        path: gitui/key_bindings.ron
        platform: win32

- crossplatform-shell:
    - command: nix-env -iA nixpkgs.gitui
      platform: linux
