- crossplatform-shell:
  - command: sudo add-apt-repository ppa:appimagelauncher-team/stable && sudo apt update && sudo apt install appimagelauncher -y
    platform: linux 
    environment: "!WSL_DISTRO_NAME"

  - command: wget -O ~/bin/marktext.AppImage https://github.com/marktext/marktext/releases/latest/download/marktext-x86_64.AppImage && chmod +x ~/bin/marktext.AppImage
    platform: linux 
    environment: "!WSL_DISTRO_NAME"
