- create:
    - ~/.config/polybar
    - ~/.config/rofi
    - ~/.config/i3

- crossplatform-link:
    - ~/.config/polybar/config.ini:
        path: polybar/config.ini
        platform: linux
        environment: "!WSL_DISTRO_NAME"
    - ~/.config/polybar/polybar.sh:
        path: polybar/polybar.sh
        platform: linux
        environment: "!WSL_DISTRO_NAME"
    - ~/.config/rofi/config.rasi:
        path: rofi/config.rasi
        platform: linux
        environment: "!WSL_DISTRO_NAME"
    - ~/.config/i3/config:
        path: i3/config
        platform: linux
        environment: "!WSL_DISTRO_NAME"
