- link:
    ~/.config/kitty: kitty

- crossplatform-link:
    # - ~/.config/kitty/kitty.conf:
    #     path: kitty/kitty.conf
    #     platform: linux
    #     environment: "!WSL_DISTRO_NAME"
    # - ~/.config/kitty/diff.conf:
    #     path: kitty/diff.conf
    #     platform: linux
    #     environment: "!WSL_DISTRO_NAME"
    # - ~/.config/kitty/dracula.conf:
    #     path: kitty/dracula.conf
    #     platform: linux
    #     environment: "!WSL_DISTRO_NAME"
    - ~/.local/bin/kitty:
        platform: linux
        environment: "!WSL_DISTRO_NAME"
        path: ~/.local/kitty.app/bin/kitty
