- crossplatform-link:
    - ~/.config/nvim:
        platform: linux
        path: nvim/nvim
    - ~/AppData/Local/nvim:
        platform: win32
        path: nvim/nvim

- crossplatform-shell:
    - command: rm -f ~/bin/nvim && wget -O ~/bin/nvim https://github.com/neovim/neovim/releases/download/stable/nvim.appimage && chmod +x ~/bin/nvim
      platform: linux
    - command: scoop install neovim
      platform: win32
