- link:
    ~/.config/nvim: nvim/nvim 
    ~/.config/efm-langserver: nvim/efm-langserver

- shell:
    - wget -O ~/bin/nvim https://github.com/neovim/neovim/releases/download/stable/nvim.appimage && chmod +x ~/bin/nvim
    # - sudo apt install luarocks && luarocks install luaformatter 
    # - npm i -g bash-language-server
    # - npm i -g docker-language-server-nodejs
    # - go intall github.com/mattn/efm-langserver@latest
    # - npm i -g vscode-langservers-extracted
    # - npm i -g typescript-language-server
    # - npm i -g yaml-language-server
