- crossplatform-link:
    - ~/.config/nvim:
        platform: linux
        path: nvim/nvim
    - ~/.config/nvim:
        platform: darwin
        path: nvim/nvim
    - ~/AppData/Local/nvim:
        platform: win32
        path: nvim/nvim
    - ~/.config/nvim-vscode:
        platform: linux
        path: nvim/nvim-vscode
    - ~/.config/nvim-vscode:
        platform: darwin
        path: nvim/nvim-vscode

- crossplatform-shell:
    - command: rm -f ~/bin/nvim && wget -O ~/bin/nvim https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.appimage && chmod +x ~/bin/nvim
      platform: linux
    - command: scoop install neovim
      platform: win32
    - command: brew install neovim
      platform: darwin
