- crossplatform-shell:
    - command: nix-env -iA nixpkgs.pipx
      platform: linux
    - command: python -m pip install --user pipx && python -m pipx ensurepath
      platform: win32
    - pipx install yamllint
