- link: 
    ~/wsl-start-vpn-kit.sh: scripts/wsl2/wsl-start-vpnkit.sh
    ~/wsl2-ubuntu-map-win-localhost.sh: scripts/wsl2/wsl2-ubuntu-map-win-localhost.sh
    ~/bin/prettier-changes: scripts/prettier-changes.sh
    ~/bin/jenkinslint: scripts/jenkinslint.sh
    ~/bin/weather: scripts/weather.sh
    ~/bin/rain: scripts/rain.sh
    ~/bin/tmux-sessionizer: scripts/tmux-sessionizer.sh
    ~/bin/git-review-diff: scripts/git-review-diff.sh
