- create:
    - ~/.config/fzf-run

- crossplatform-link:
    - ~/wsl-start-vpn-kit.sh:
        path: scripts/wsl2/wsl-start-vpnkit.sh
        platform: linux
    - ~/wsl-forward-windows-port.sh:
        path: scripts/wsl2/wsl-forward-windows-port.sh
        platform: linux
    - ~/bin/prettier-changes:
        path: scripts/prettier-changes.sh
        platform: linux
    - ~/bin/jenkinslint:
        path: scripts/jenkinslint.sh
    - ~/bin/weather:
        path: scripts/weather.sh
        platform: linux
    - ~/bin/rain:
        path: scripts/rain.sh
        platform: linux
    - ~/bin/tmux-sessionizer:
        path: scripts/tmux-sessionizer.sh
        platform: linux
    - ~/bin/git-review-diff:
        path: scripts/git-review-diff.sh
    - ~/bin/worktree-create:
        path: scripts/git-create-worktree.sh
    - ~/bin/git-stat:
        path: scripts/git-stat.sh
    - ~/bin/git-ch:
        path: scripts/git-fzf-checkout.sh
    - ~/bin/build-merlin-libs:
        path: scripts/build-merlin-libs.sh
        platform: linux
    - ~/bin/prettier-format-staged:
        path: scripts/prettier-format-staged.sh
        platform: linux
    - ~/bin/find_up.sh:
        path: scripts/find_up.sh
    - ~/bin/clean-node-modules:
        path: scripts/clean-node-modules.sh
        platform: linux
    - ~/bin/live-grep:
        path: scripts/live-grep.sh
        platform: linux
    - ~/bin/tmux-vifm-sessionizer:
        path: scripts/tmux-vifm-sessionizer.sh
        platform: linux
    - ~/bin/git-all-executable:
        path: scripts/git-all-executable.sh
    - ~/bin/fzf-dir:
        path: scripts/fzf-dir.sh
    - ~/bin/eclipse-open:
        path: scripts/eclipse-open.sh
        platform: win32
    - ~/bin/kdiff-merge.sh:
        path: scripts/kdiff-merge.sh
        platform: linux
    - ~/.config/fzf-run/fzf-run.json:
        path: scripts/fzf-run/fzf-run.json
        platform: linux
    - ~/bin/man:
        path: scripts/man-on-windows.sh
        platform: win32
    - ~/bin/jira-issues-to-confluence-markup:
        path: scripts/jira-issues-to-confluence-markup.sh
    - ~/bin/fnpm:
        path: scripts/fnpm.sh
    - ~/bin/i3exit.sh:
        path: scripts/i3exit.sh
        platform: linux
