- link: 
    ~/wsl-start-vpn-kit.sh: scripts/wsl2/wsl-start-vpnkit.sh
    ~/wsl2-ubuntu-map-win-localhost.sh: scripts/wsl2/wsl2-ubuntu-map-win-localhost.sh
    ~/wsl-forward-windows-ports.sh: scripts/wsl2/wsl-forward-windows-ports.sh
    ~/bin/prettier-changes: scripts/prettier-changes.sh
    ~/bin/jenkinslint: scripts/jenkinslint.sh
    ~/bin/weather: scripts/weather.sh
    ~/bin/rain: scripts/rain.sh
    ~/bin/tmux-sessionizer: scripts/tmux-sessionizer.sh
    ~/bin/git-review-diff: scripts/git-review-diff.sh
    ~/bin/worktree-create: scripts/git-create-worktree.sh
    ~/bin/git-stat: scripts/git-stat.sh
    ~/bin/build-merlin-libs: scripts/build-merlin-libs.sh
    ~/bin/prettier-format-staged: scripts/prettier-format-staged.sh
    ~/bin/find_up.sh: scripts/find_up.sh
    ~/bin/clean-node-modules: scripts/clean-node-modules.sh
    ~/bin/live-grep: scripts/live-grep.sh
    ~/bin/tmux-vifm-sessionizer: scripts/tmux-vifm-sessionizer.sh
    ~/bin/git-all-executable: scripts/git-all-executable.sh
    ~/bin/kdiff-merge.sh: scripts/kdiff-merge.sh
    ~/.config/fzf-run/fzf-run.json: scripts/fzf-run/fzf-run.json
