- link:
    ~/.tmux.conf: tmux/tmux.conf

- crossplatform-shell:
    - command: sudo apt remove tmux -y && rm -f ~/bin/tmux && wget -O ~/bin/tmux https://github.com/nelsonenzo/tmux-appimage/releases/latest/download/tmux.appimage && chmod +x ~/bin/tmux
      platform: linux
