- link:
    ~/.tmux.conf: tmux/tmux.conf

- crossplatform-shell:
    - command: nix-env -iA nixpkgs.tmux
      platform: linux
    - command: brew install tmux
      platform: darwin
    - command: cargo install --git https://github.com/1DIce/tmux-sessioneer.git
