- crossplatform-shell:
    - command: nix-env -iA nixpkgs.volta
      platform: linux
    - command: scoop install main/volta
      platform: win32
    - command: curl https://get.volta.sh | bash -s -- --skip-setup
      platform: darwin
    - command: volta install node@22 && volta install yarn
