- crossplatform-shell:
    - command: nix-env -iA nixpkgs.volta
      platform: linux
    - command: scoop install main/volta
      platform: win32
    - command: volta install node@20 && volta install yarn
