- crossplatform-shell:
    - command: curl https://get.volta.sh | bash -s -- --skip-setup
      platform: linux
    - command: scoop install main/volta
      platform: win32
    - command: volta install node@14 && volta install yarn
