- crossplatform-link:
  - ~/.wslconfig:
      platform: win32
      force: true
      path: wsl/wslconfig

- crossplatform-shell:
  # wsl.conf does not get picked up when it is symlinked
    - command: sudo cp ./wsl/wsl.conf /etc/wsl.conf
      platform: linux
      environment: WSL_DISTRO_NAME

