- link:
    ~/.config/zathura/zathurarc: zathura/zathurarc

- crossplatform-shell:
    - command: sudo apt update && sudo apt install zathura
      platform: linux
      environment: "!WSL_DISTRO_NAME"
