[general]

import = ["~/.config/alacritty/alacritty_tokyonight_night.toml"]

[terminal]

[terminal.shell]
program = "zsh"
args = ["-l"]

[font]

# The `style` can be specified to pick a specific face.
normal = { family = "UbuntuMono Nerd Font Mono", style = "Regular" }

size = 16.0

#[keyboard]
#bindings = [
#{ key = "T", mods = "Option", action = "None" },
#{ key = "T", mods = "Command", action = "None" },
#]

[selection]
save_to_clipboard = true


[window]
option_as_alt = "OnlyLeft"




