
import = ["~/.config/alacritty/alacritty_tokyonight_night.toml",]

[shell]
program = "/usr/bin/zsh"
args = ["-l"]

# [font]
# normal = {
#     family = "UbuntuMono Nerd Font",
#     # The `style` can be specified to pick a specific face.
#     style = "Regular"
# }
#
# size = 13
