- defaults:
    link:
      relink: true
      create: true
    shell:
      stdout: true

- clean: ["~"]

- create:
    - ~/Downloads
    - ~/bin
    - ~/.fonts
    - ~/work
    - ~/personal
    - ~/open-source
