# .zshenv is sourced on all invocations of the shell,
# unless the -f option is set. It should contain commands
# to set the command search path, plus other important environment
# variables. .zshenv should not contain commands that produce output
# or assume the shell is attached to a tty.

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=${HOME}/.config}

# load bashmarks
source ~/.local/bin/bashmarks.sh


if [ -d "$HOME/.deno/bin" ] ; then
  export PATH=~/.deno/bin:$PATH
fi

export PATH=~/bin:$PATH
export PATH=~/.local/bin:$PATH

# Rust
if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi
if [ -d "$HOME/.rustup/toolchains/stable-aarch64-apple-darwin/bin" ] ; then
    PATH="$HOME/.rustup/toolchains/stable-aarch64-apple-darwin/bin:$PATH"
fi

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"


# opencode
if [[ -d "$HOME/.opencode/bin" ]]; then
  export PATH="$HOME/.opencode/bin:$PATH"
fi
