# .zshenv is sourced on all invocations of the shell,
# unless the -f option is set. It should contain commands
# to set the command search path, plus other important environment
# variables. .zshenv should not contain commands that produce output
# or assume the shell is attached to a tty.

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=${HOME}/.config}

# load bashmarks
source ~/.local/bin/bashmarks.sh


if [ -d "/home/linuxbrew/.linuxbrew/bin" ] ; then
  export BREW_HOME="/home/linuxbrew/.linuxbrew/bin"
  export PATH="$PATH:$BREW_HOME"
fi

if [ -d "$HOME/.deno/bin" ] ; then
  export PATH=~/.deno/bin:$PATH
fi

export PATH=~/bin:$PATH
export PATH=~/.local/bin:$PATH

# Rust
if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

alias fd="fdfind"
alias bat="batcat"

# append windows PATH while in wsl
if [ ! -z "$WSL_DISTRO_NAME" ]; then
  PATH="/mnt/c/Windows/system32:$PATH"
  PATH="/mnt/c/Windows:$PATH"
  PATH="/mnt/c/Windows/System32/Wbem:$PATH"
  PATH="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:$PATH"
  PATH="/mnt/c/Windows/System32/OpenSSH/:$PATH"
  PATH="/mnt/c/Users/Lars.Debor/AppData/Local/Programs/Microsoft VS Code/bin:$PATH"
fi
